<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../Classes/FusionLibServer.class.php';

/**
 * Test class for FusionLibServer.
 * Generated by PHPUnit on 2010-05-07 at 16:13:04.
 */
class FusionLibServerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    FusionLibServer
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = FusionLibServer::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetConfigs().
     */
    public function testSetConfigs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testStart().
     */
    public function testStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
