<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../Classes/Action/InventoryAction.class.php';

/**
 * Test class for InventoryAction.
 * Generated by PHPUnit on 2010-05-07 at 16:27:07.
 */
class InventoryActionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    InventoryAction
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new InventoryAction;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testCheckConfigs().
     */
    public function testCheckConfigs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetXMLData().
     */
    public function testSetXMLData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
